### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by JoaquinGiordano** [JoaquinGiordano/fltabs#1]
Redesign the tabs.

Be free with the design.

**Comment by CoryKelly** [comment]
I'll work on this..

**Comment by JoaquinGiordano** [comment]
@CoryKelly I don't know why but I can't assign the issue so do it and make a pull request when finish

**Comment by CoryKelly** [comment]
> @CoryKelly I don't know why but I can't assign the issue so do it and make a pull request when finish

Sounds good, working on it now
